cask "font-iosevka-etoile" do
  version "34.6.3"
  sha256 "fe2b166bff3b49c15dfc820932514bd2e6ebc400fa3d3f64e035465a1095b37f"

  url "https://github.com/be5invis/Iosevka/releases/download/v#{version}/PkgTTF-Unhinted-IosevkaEtoile-#{version}.zip"
  name "Iosevka Etoile"
  homepage "https://typeof.net/Iosevka/"

  font "IosevkaEtoile-Bold.ttf"
  font "IosevkaEtoile-BoldItalic.ttf"
  font "IosevkaEtoile-BoldOblique.ttf"
  font "IosevkaEtoile-ExtraBold.ttf"
  font "IosevkaEtoile-ExtraBoldItalic.ttf"
  font "IosevkaEtoile-ExtraBoldOblique.ttf"
  font "IosevkaEtoile-ExtraLight.ttf"
  font "IosevkaEtoile-ExtraLightItalic.ttf"
  font "IosevkaEtoile-ExtraLightOblique.ttf"
  font "IosevkaEtoile-Heavy.ttf"
  font "IosevkaEtoile-HeavyItalic.ttf"
  font "IosevkaEtoile-HeavyOblique.ttf"
  font "IosevkaEtoile-Italic.ttf"
  font "IosevkaEtoile-Light.ttf"
  font "IosevkaEtoile-LightItalic.ttf"
  font "IosevkaEtoile-LightOblique.ttf"
  font "IosevkaEtoile-Medium.ttf"
  font "IosevkaEtoile-MediumItalic.ttf"
  font "IosevkaEtoile-MediumOblique.ttf"
  font "IosevkaEtoile-Oblique.ttf"
  font "IosevkaEtoile-Regular.ttf"
  font "IosevkaEtoile-SemiBold.ttf"
  font "IosevkaEtoile-SemiBoldItalic.ttf"
  font "IosevkaEtoile-SemiBoldOblique.ttf"
  font "IosevkaEtoile-Thin.ttf"
  font "IosevkaEtoile-ThinItalic.ttf"
  font "IosevkaEtoile-ThinOblique.ttf"
end
