cask "font-iosevka-aile" do
  version "34.7.0"
  sha256 "10f0053c5579e67e04ec568da18935f184e2267b4c06c82aa0888c6c5dca7ddc"

  url "https://github.com/be5invis/Iosevka/releases/download/v#{version}/PkgTTF-Unhinted-IosevkaAile-#{version}.zip"
  name "Iosevka Aile"
  homepage "https://typeof.net/Iosevka/"

  font "IosevkaAile-Bold.ttf"
  font "IosevkaAile-BoldItalic.ttf"
  font "IosevkaAile-BoldOblique.ttf"
  font "IosevkaAile-ExtraBold.ttf"
  font "IosevkaAile-ExtraBoldItalic.ttf"
  font "IosevkaAile-ExtraBoldOblique.ttf"
  font "IosevkaAile-ExtraLight.ttf"
  font "IosevkaAile-ExtraLightItalic.ttf"
  font "IosevkaAile-ExtraLightOblique.ttf"
  font "IosevkaAile-Heavy.ttf"
  font "IosevkaAile-HeavyItalic.ttf"
  font "IosevkaAile-HeavyOblique.ttf"
  font "IosevkaAile-Italic.ttf"
  font "IosevkaAile-Light.ttf"
  font "IosevkaAile-LightItalic.ttf"
  font "IosevkaAile-LightOblique.ttf"
  font "IosevkaAile-Medium.ttf"
  font "IosevkaAile-MediumItalic.ttf"
  font "IosevkaAile-MediumOblique.ttf"
  font "IosevkaAile-Oblique.ttf"
  font "IosevkaAile-Regular.ttf"
  font "IosevkaAile-SemiBold.ttf"
  font "IosevkaAile-SemiBoldItalic.ttf"
  font "IosevkaAile-SemiBoldOblique.ttf"
  font "IosevkaAile-Thin.ttf"
  font "IosevkaAile-ThinItalic.ttf"
  font "IosevkaAile-ThinOblique.ttf"
end
