cask "font-iosevka-aile" do
  version "34.6.3"
  sha256 "74e52eea7724732f6366f2f131c74349acb47ca5463884692c8bd90c18b120d5"

  url "https://github.com/be5invis/Iosevka/releases/download/v#{version}/PkgTTF-Unhinted-IosevkaAile-#{version}.zip"
  name "Iosevka Aile"
  homepage "https://typeof.net/Iosevka/"

  font "IosevkaAile-Bold.ttf"
  font "IosevkaAile-BoldItalic.ttf"
  font "IosevkaAile-BoldOblique.ttf"
  font "IosevkaAile-ExtraBold.ttf"
  font "IosevkaAile-ExtraBoldItalic.ttf"
  font "IosevkaAile-ExtraBoldOblique.ttf"
  font "IosevkaAile-ExtraLight.ttf"
  font "IosevkaAile-ExtraLightItalic.ttf"
  font "IosevkaAile-ExtraLightOblique.ttf"
  font "IosevkaAile-Heavy.ttf"
  font "IosevkaAile-HeavyItalic.ttf"
  font "IosevkaAile-HeavyOblique.ttf"
  font "IosevkaAile-Italic.ttf"
  font "IosevkaAile-Light.ttf"
  font "IosevkaAile-LightItalic.ttf"
  font "IosevkaAile-LightOblique.ttf"
  font "IosevkaAile-Medium.ttf"
  font "IosevkaAile-MediumItalic.ttf"
  font "IosevkaAile-MediumOblique.ttf"
  font "IosevkaAile-Oblique.ttf"
  font "IosevkaAile-Regular.ttf"
  font "IosevkaAile-SemiBold.ttf"
  font "IosevkaAile-SemiBoldItalic.ttf"
  font "IosevkaAile-SemiBoldOblique.ttf"
  font "IosevkaAile-Thin.ttf"
  font "IosevkaAile-ThinItalic.ttf"
  font "IosevkaAile-ThinOblique.ttf"
end
