cask "font-iosevka-etoile" do
  version "34.7.0"
  sha256 "a502dc0b423220c4c77955f7631c5796d6be9fc4e06f0fd1eae7c1b954e96a21"

  url "https://github.com/be5invis/Iosevka/releases/download/v#{version}/PkgTTF-Unhinted-IosevkaEtoile-#{version}.zip"
  name "Iosevka Etoile"
  homepage "https://typeof.net/Iosevka/"

  font "IosevkaEtoile-Bold.ttf"
  font "IosevkaEtoile-BoldItalic.ttf"
  font "IosevkaEtoile-BoldOblique.ttf"
  font "IosevkaEtoile-ExtraBold.ttf"
  font "IosevkaEtoile-ExtraBoldItalic.ttf"
  font "IosevkaEtoile-ExtraBoldOblique.ttf"
  font "IosevkaEtoile-ExtraLight.ttf"
  font "IosevkaEtoile-ExtraLightItalic.ttf"
  font "IosevkaEtoile-ExtraLightOblique.ttf"
  font "IosevkaEtoile-Heavy.ttf"
  font "IosevkaEtoile-HeavyItalic.ttf"
  font "IosevkaEtoile-HeavyOblique.ttf"
  font "IosevkaEtoile-Italic.ttf"
  font "IosevkaEtoile-Light.ttf"
  font "IosevkaEtoile-LightItalic.ttf"
  font "IosevkaEtoile-LightOblique.ttf"
  font "IosevkaEtoile-Medium.ttf"
  font "IosevkaEtoile-MediumItalic.ttf"
  font "IosevkaEtoile-MediumOblique.ttf"
  font "IosevkaEtoile-Oblique.ttf"
  font "IosevkaEtoile-Regular.ttf"
  font "IosevkaEtoile-SemiBold.ttf"
  font "IosevkaEtoile-SemiBoldItalic.ttf"
  font "IosevkaEtoile-SemiBoldOblique.ttf"
  font "IosevkaEtoile-Thin.ttf"
  font "IosevkaEtoile-ThinItalic.ttf"
  font "IosevkaEtoile-ThinOblique.ttf"
end
